//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPR.Languages {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SPRLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SPRLang() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SPR.Languages.SPRLang", typeof(SPRLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Additionnal Applications.
        /// </summary>
        public static string Additionnal_App_Paths {
            get {
                return ResourceManager.GetString("Additionnal_App_Paths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Additionnal Options.
        /// </summary>
        public static string Additionnal_Options {
            get {
                return ResourceManager.GetString("Additionnal_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the destination folder of your system.
        ///By example you can select &quot;E:\Platforms\Games\Nintendo Entertainment System&quot;..
        /// </summary>
        public static string Choose_Dest_Folder {
            get {
                return ResourceManager.GetString("Choose_Dest_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose a Platform.
        /// </summary>
        public static string Choose_Platform {
            get {
                return ResourceManager.GetString("Choose_Platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the source folder of your system containing your datas.
        ///By example you can select &quot;E:\Launchbox\Games\Nintendo Entertainment System&quot;..
        /// </summary>
        public static string Choose_Source_Folder {
            get {
                return ResourceManager.GetString("Choose_Source_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configure Destination.
        /// </summary>
        public static string Configure_Destination {
            get {
                return ResourceManager.GetString("Configure_Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configure paths.
        /// </summary>
        public static string Configure_Paths {
            get {
                return ResourceManager.GetString("Configure_Paths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configure Source.
        /// </summary>
        public static string Configure_Source {
            get {
                return ResourceManager.GetString("Configure_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configure sub folders.
        /// </summary>
        public static string Configure_SubFolders {
            get {
                return ResourceManager.GetString("Configure_SubFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Games destination.
        /// </summary>
        public static string Dest_Games {
            get {
                return ResourceManager.GetString("Dest_Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Destination subfolders.
        /// </summary>
        public static string Dest_Sub {
            get {
                return ResourceManager.GetString("Dest_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Destination.
        /// </summary>
        public static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Destination Folder.
        /// </summary>
        public static string Destination_Folder {
            get {
                return ResourceManager.GetString("Destination_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Destination folders.
        /// </summary>
        public static string Destination_Folders {
            get {
                return ResourceManager.GetString("Destination_Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Directory doesn&apos;t exist.
        /// </summary>
        public static string DirDontExist {
            get {
                return ResourceManager.GetString("DirDontExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The paths mustn&apos;t end with a &apos;\&apos;.
        /// </summary>
        public static string Err_FinishSlash {
            get {
                return ResourceManager.GetString("Err_FinishSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Must be a relative link.
        /// </summary>
        public static string Err_MustRelat {
            get {
                return ResourceManager.GetString("Err_MustRelat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select a mode.
        /// </summary>
        public static string Err_SelectMode {
            get {
                return ResourceManager.GetString("Err_SelectMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Files migration.
        /// </summary>
        public static string Files_Migration {
            get {
                return ResourceManager.GetString("Files_Migration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Folders.
        /// </summary>
        public static string Folders {
            get {
                return ResourceManager.GetString("Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forced Mode.
        /// </summary>
        public static string Forced_Mode {
            get {
                return ResourceManager.GetString("Forced_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Game Folder.
        /// </summary>
        public static string Game_Folder {
            get {
                return ResourceManager.GetString("Game_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Games.
        /// </summary>
        public static string Games {
            get {
                return ResourceManager.GetString("Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hard Path.
        /// </summary>
        public static string Hard_Path {
            get {
                return ResourceManager.GetString("Hard_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Migrate will use paths you give to determinate how to copy datas, last directory of paths is always used to keep datas in the folder you want to use. 
        ///Structure will look like as &quot;..\Platforms\Games\MySytemName&quot;, &quot;..\Platforms\Manuals\MySystemName&quot;, etc... 
        ///You can use personnalized subfolders to change name of manuals, games, images, videos, musics directories. .
        /// </summary>
        public static string Help_Migrate {
            get {
                return ResourceManager.GetString("Help_Migrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hidden Games.
        /// </summary>
        public static string Hidden_Games {
            get {
                return ResourceManager.GetString("Hidden_Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Images.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Images Folder.
        /// </summary>
        public static string Images_Folder {
            get {
                return ResourceManager.GetString("Images_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Infos Platform.
        /// </summary>
        public static string Infos_Platform {
            get {
                return ResourceManager.GetString("Infos_Platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Interpreted current Main Path.
        /// </summary>
        public static string Interpreted_Current_Main_Path {
            get {
                return ResourceManager.GetString("Interpreted_Current_Main_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Follow the normal step now to reinitialize.
        /// </summary>
        public static string IReset_Factory {
            get {
                return ResourceManager.GetString("IReset_Factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Keep SubFolder Mode.
        /// </summary>
        public static string Keep_SubFolder_Mode {
            get {
                return ResourceManager.GetString("Keep_SubFolder_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mode is set on &quot;Forced&quot; by default..
        /// </summary>
        public static string M_DefaultForced {
            get {
                return ResourceManager.GetString("M_DefaultForced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Main.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manual Folder.
        /// </summary>
        public static string Manual_Folder {
            get {
                return ResourceManager.GetString("Manual_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manuals.
        /// </summary>
        public static string Manuals {
            get {
                return ResourceManager.GetString("Manuals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Migrate Files.
        /// </summary>
        public static string Migrate_Files {
            get {
                return ResourceManager.GetString("Migrate_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Migration.
        /// </summary>
        public static string Migration {
            get {
                return ResourceManager.GetString("Migration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modify Games paths.
        /// </summary>
        public static string Modify_Games_Path {
            get {
                return ResourceManager.GetString("Modify_Games_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modify Platform paths.
        /// </summary>
        public static string Modify_Platform_Path {
            get {
                return ResourceManager.GetString("Modify_Platform_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Musics.
        /// </summary>
        public static string Musics {
            get {
                return ResourceManager.GetString("Musics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Musics Folder.
        /// </summary>
        public static string Musics_Folder {
            get {
                return ResourceManager.GetString("Musics_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name of Folders.
        /// </summary>
        public static string Name_of_Folders {
            get {
                return ResourceManager.GetString("Name_of_Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No modification needed for this path.
        /// </summary>
        public static string No_Modif {
            get {
                return ResourceManager.GetString("No_Modif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open in Explorer.
        /// </summary>
        public static string Open_In_Explorer {
            get {
                return ResourceManager.GetString("Open_In_Explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Or.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Path.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Path doesn&apos;t exist.
        /// </summary>
        public static string Path_D_Exist {
            get {
                return ResourceManager.GetString("Path_D_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paths modified.
        /// </summary>
        public static string Paths_Modified {
            get {
                return ResourceManager.GetString("Paths_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paths Not modified.
        /// </summary>
        public static string Paths_Not_Modified {
            get {
                return ResourceManager.GetString("Paths_Not_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Platform.
        /// </summary>
        public static string Platform {
            get {
                return ResourceManager.GetString("Platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Platform Folder Name.
        /// </summary>
        public static string Platform_Folder_Name {
            get {
                return ResourceManager.GetString("Platform_Folder_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please Select a mode.
        /// </summary>
        public static string Please_Select_Mode {
            get {
                return ResourceManager.GetString("Please_Select_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preview modifications.
        /// </summary>
        public static string Preview_Modifications {
            get {
                return ResourceManager.GetString("Preview_Modifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Process.
        /// </summary>
        public static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Would you want to use advanced verification ?.
        /// </summary>
        public static string Q_WichMode {
            get {
                return ResourceManager.GetString("Q_WichMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à It uses hash calculation to garantee files are exactly the same but 3x more longer than a simple mode..
        /// </summary>
        public static string Q_WichMode2 {
            get {
                return ResourceManager.GetString("Q_WichMode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Would you want to change Games paths too ?.
        /// </summary>
        public static string QChange_GamesPaths {
            get {
                return ResourceManager.GetString("QChange_GamesPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Relative Path.
        /// </summary>
        public static string Relative_Path {
            get {
                return ResourceManager.GetString("Relative_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reset Factory.
        /// </summary>
        public static string Reset_Factory {
            get {
                return ResourceManager.GetString("Reset_Factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Root.
        /// </summary>
        public static string Root {
            get {
                return ResourceManager.GetString("Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Root folder.
        /// </summary>
        public static string Root_Folder {
            get {
                return ResourceManager.GetString("Root_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select a folder in the windows.
        /// </summary>
        public static string Select_Folder {
            get {
                return ResourceManager.GetString("Select_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Simulation Fail....
        /// </summary>
        public static string SimuFail {
            get {
                return ResourceManager.GetString("SimuFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Simulate.
        /// </summary>
        public static string Simulate {
            get {
                return ResourceManager.GetString("Simulate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Simulation.
        /// </summary>
        public static string Simulation {
            get {
                return ResourceManager.GetString("Simulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Simulation Success....
        /// </summary>
        public static string SimuSuccess {
            get {
                return ResourceManager.GetString("SimuSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source folder.
        /// </summary>
        public static string Source_Folder {
            get {
                return ResourceManager.GetString("Source_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Games source.
        /// </summary>
        public static string Source_Games {
            get {
                return ResourceManager.GetString("Source_Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source subfolders.
        /// </summary>
        public static string Source_Sub {
            get {
                return ResourceManager.GetString("Source_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Transfert errors.
        /// </summary>
        public static string Transfert_Fail {
            get {
                return ResourceManager.GetString("Transfert_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Transfert successfull.
        /// </summary>
        public static string Transfert_Success {
            get {
                return ResourceManager.GetString("Transfert_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select.
        /// </summary>
        public static string TT_Destination_Folder {
            get {
                return ResourceManager.GetString("TT_Destination_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can parameter wich sub folder will be used for destination paths.
        /// </summary>
        public static string TT_Folders {
            get {
                return ResourceManager.GetString("TT_Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Double click to edit a plaform, right click for menu..
        /// </summary>
        public static string TT_ListView {
            get {
                return ResourceManager.GetString("TT_ListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose the futur folder of the system (ex: &quot;..\..\Platforms\Games\Master System&quot;).
        /// </summary>
        public static string TT_Migrate_Destination {
            get {
                return ResourceManager.GetString("TT_Migrate_Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose the folder of the system (ex &quot;.\Games\Master System&quot;)..
        /// </summary>
        public static string TT_Migrate_Source {
            get {
                return ResourceManager.GetString("TT_Migrate_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To define the name of the folder that will be used in each section..
        /// </summary>
        public static string TT_PlaformFolder {
            get {
                return ResourceManager.GetString("TT_PlaformFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hit enter to validate manually your path or click on browse to select a folder.
        /// </summary>
        public static string TT_SelectFolder {
            get {
                return ResourceManager.GetString("TT_SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can change subfolders used to determinate paths.
        /// </summary>
        public static string TT_Sub {
            get {
                return ResourceManager.GetString("TT_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use the textbox then hit &apos;Enter&apos;.
        /// </summary>
        public static string Use_TextBox {
            get {
                return ResourceManager.GetString("Use_TextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Verification.
        /// </summary>
        public static string Verif {
            get {
                return ResourceManager.GetString("Verif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Videos.
        /// </summary>
        public static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Videos Folder.
        /// </summary>
        public static string Videos_Folder {
            get {
                return ResourceManager.GetString("Videos_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This folder is named &quot;Music&quot;, without &apos;s&apos;. Think to change it, in &apos;Source Sub Folder&apos; if your migrate files from this location..
        /// </summary>
        public static string W_Music_Message {
            get {
                return ResourceManager.GetString("W_Music_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Waiting....
        /// </summary>
        public static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pay attention to the Launchbox music folder:.
        /// </summary>
        public static string Warning_Music {
            get {
                return ResourceManager.GetString("Warning_Music", resourceCulture);
            }
        }
    }
}
